export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_UP_DONE_RESET = 'SIGN_UP_DONE_RESET';

export const AVATAR_CHANGE_REQUEST = 'AVATAR_CHANGE_REQUEST';
export const AVATAR_CHANGE_SUCCESS = 'AVATAR_CHANGE_SUCCESS';
export const AVATAR_CHANGE_FAILURE = 'AVATAR_CHANGE_FAILURE';

export const NICKNAME_CHANGE_REQUEST = 'NICKNAME_CHANGE_REQUEST';
export const NICKNAME_CHANGE_SUCCESS = 'NICKNAME_CHANGE_SUCCESS';
export const NICKNAME_CHANGE_FAILURE = 'NICKNAME_CHANGE_FAILURE';

export const DESCRIPTION_CHANGE_REQUEST = 'DESCRIPTION_CHANGE_REQUEST';
export const DESCRIPTION_CHANGE_SUCCESS = 'DESCRIPTION_CHANGE_SUCCESS';
export const DESCRIPTION_CHANGE_FAILURE = 'DESCRIPTION_CHANGE_FAILURE';

export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE';
